"use client";

/**
 * ContentSection — MODE adapter for ShadcnContentSection from @/components/external/ShadcnContentSection.
 *
 * Generated by MODE ingestion tool (agent/ingest.js).
 * DO NOT manually edit VARIANT_MAP or PALETTE_MAP — update the declaration
 * file and regenerate via: node agent/ingest.js declarations/<file>.json --write
 *
 * Palette bridge:
 *   light   → {}
 *   neutral → {"className":"neutral"}
 *   dark    → {"className":"dark"}
 */

import { ShadcnContentSection } from "@/components/external/ShadcnContentSection";
import type { ComponentSlots, PaletteMode } from "@/lib/types";

const VARIANT_MAP: Record<string, Record<string, unknown>> = {
  "standard": {},
  "with-sidebar": {"layout":"sidebar"},
  "with-callout": {"showCallout":true},
};

const PALETTE_MAP: Record<string, Record<string, unknown>> = {
  light:   {},
  neutral:   {"className":"neutral"},
  dark:   {"className":"dark"},
};

export function ContentSection({ slots, variant, palette }: {
  slots: ComponentSlots;
  variant: string | null;
  palette?: PaletteMode;
}) {
  return (
    <ShadcnContentSection
      headline={slots.headline as string}
      body={slots.body as string}
      callout={slots.callout as string ?? undefined}
      cta={slots.cta ? { label: (slots.cta as any).label, href: (slots.cta as any).href } : undefined}
      {...(VARIANT_MAP[variant ?? ""] ?? {})}
      {...(PALETTE_MAP[palette ?? "light"] ?? {})}
    />
  );
}
