#!/usr/bin/env node
"use strict";

/**
 * MODE Ingestion Tool
 *
 * Reads a declaration JSON file and generates:
 *   1. Adapter .tsx source   — wraps the external component in MODE's interface
 *   2. Manifest entry        — components.json block (inherits from modeType if it exists)
 *   3. Registry line         — what to add to ui/components/modules/index.ts
 *
 * Usage:
 *   node agent/ingest.js <declaration-file.json> [--write]
 *
 * Without --write: prints all three outputs to stdout for review.
 * With --write:    writes the adapter file to ui/components/modules/ and
 *                  prints instructions for the manifest entry and registry line.
 *
 * Examples:
 *   node agent/ingest.js declarations/acme-hero.json
 *   node agent/ingest.js declarations/acme-hero.json --write
 */

const fs = require("fs");
const path = require("path");
const { validateDeclaration } = require("./ingestion-schema");

// Root of the mode/ project (one level up from agent/)
const PROJECT_ROOT = path.resolve(__dirname, "..");
const COMPONENTS_JSON = path.join(PROJECT_ROOT, "manifest", "components.json");
const MODULES_DIR = path.join(PROJECT_ROOT, "ui", "components", "modules");

// ─── Slot transform code generators ────────────────────────────────────────

/**
 * Generate the JSX prop value expression for a slot.
 * @param {string} slotName - MODE slot name (e.g. "headline")
 * @param {object} slotDef  - { prop, type? }
 * @returns {string} - JSX attribute string (e.g. `title={slots.headline as string}`)
 */
function slotPropExpr(slotName, slotDef) {
  const prop = slotDef.prop;
  const type = slotDef.type || "string";
  const ref = `slots.${slotName}`;

  let value;
  switch (type) {
    case "string":
      value = `${ref} as string`;
      break;
    case "string?":
      value = `${ref} as string ?? undefined`;
      break;
    case "number":
      value = `${ref} as number`;
      break;
    case "cta":
      value = `{ label: (${ref} as any).label, href: (${ref} as any).href }`;
      break;
    case "cta?":
      value = `${ref} ? { label: (${ref} as any).label, href: (${ref} as any).href } : undefined`;
      break;
    case "array":
      value = `${ref} as any[]`;
      break;
    case "passthrough":
    default:
      value = ref;
      break;
  }

  return `      ${prop}={${value}}`;
}

// ─── Adapter source generator ───────────────────────────────────────────────

/**
 * Generate the full adapter .tsx source from a validated declaration.
 * @param {object} declaration
 * @returns {string} TypeScript source
 */
function generateAdapter(declaration) {
  const { name, source, modeType, slots = {}, variants = {}, palette } = declaration;

  // Slot prop lines
  const slotLines = Object.entries(slots)
    .map(([slotName, slotDef]) => slotPropExpr(slotName, slotDef))
    .join("\n");

  // VARIANT_MAP entries
  const variantEntries = Object.entries(variants)
    .map(([key, props]) => `  "${key}": ${JSON.stringify(props)},`)
    .join("\n");

  // PALETTE_MAP entries
  const paletteLine = (mode) => `  ${mode}:   ${JSON.stringify(palette[mode])},`;

  // Whether we need the VARIANT_MAP at all
  const hasVariants = Object.keys(variants).length > 0;

  const variantMapBlock = hasVariants
    ? `\nconst VARIANT_MAP: Record<string, Record<string, unknown>> = {\n${variantEntries}\n};\n`
    : "";

  const variantSpread = hasVariants
    ? "\n      {...(VARIANT_MAP[variant ?? \"\"] ?? {})}"
    : "";

  return `"use client";

/**
 * ${modeType} — MODE adapter for ${name} from ${source}.
 *
 * Generated by MODE ingestion tool (agent/ingest.js).
 * DO NOT manually edit VARIANT_MAP or PALETTE_MAP — update the declaration
 * file and regenerate via: node agent/ingest.js declarations/<file>.json --write
 *
 * Palette bridge:
 *   light   → ${JSON.stringify(palette.light)}
 *   neutral → ${JSON.stringify(palette.neutral)}
 *   dark    → ${JSON.stringify(palette.dark)}
 */

import { ${name} } from "${source}";
import type { ComponentSlots, PaletteMode } from "@/lib/types";
${variantMapBlock}
const PALETTE_MAP: Record<string, Record<string, unknown>> = {
${paletteLine("light")}
${paletteLine("neutral")}
${paletteLine("dark")}
};

export function ${modeType}({ slots, variant, palette }: {
  slots: ComponentSlots;
  variant: string | null;
  palette?: PaletteMode;
}) {
  return (
    <${name}
${slotLines}${variantSpread}
      {...(PALETTE_MAP[palette ?? "light"] ?? {})}
    />
  );
}
`;
}

// ─── Manifest entry generator ───────────────────────────────────────────────

/**
 * Generate a components.json manifest entry for this declaration.
 * If modeType matches an existing entry, it inherits semantic metadata.
 * Otherwise returns a template the user must fill in.
 *
 * @param {object} declaration
 * @returns {object} manifest entry
 */
function generateManifestEntry(declaration) {
  const { name, source, modeType, slots = {}, variants = {} } = declaration;

  // Try to inherit from existing manifest entry
  let existing = null;
  if (fs.existsSync(COMPONENTS_JSON)) {
    try {
      const manifest = JSON.parse(fs.readFileSync(COMPONENTS_JSON, "utf8"));
      existing = (manifest.components || []).find((c) => c.name === modeType) || null;
    } catch {
      // ignore parse errors
    }
  }

  const entry = {
    name: modeType,
    purpose: existing
      ? existing.purpose
      : `[FILL IN] What this component does at the section level.`,
    tier: "module",
    beats: existing ? existing.beats : ["[FILL IN e.g. Orientation]"],
    archetypes: existing
      ? existing.archetypes
      : ["Mover", "Validator", "Explorer"],
    funnel_stages: existing
      ? existing.funnel_stages
      : ["awareness", "consideration", "decision", "conversion"],
    variants: Object.keys(variants).length > 0
      ? Object.keys(variants)
      : existing
        ? existing.variants
        : ["[FILL IN]"],
    variant_slots: existing ? existing.variant_slots || {} : {},
    slots: Object.fromEntries(
      Object.entries(slots).map(([slotName, def]) => [
        slotName,
        { type: def.type || "string", required: false },
      ])
    ),
    _ingested: {
      source,
      export_name: name,
      generated_at: new Date().toISOString(),
    },
  };

  if (existing) {
    entry._note = `Replaces built-in ${modeType}. Semantic metadata inherited from existing manifest entry.`;
  } else {
    entry._note = `New modeType — fill in purpose, beats, and funnel_stages before use.`;
  }

  return entry;
}

// ─── CLI ────────────────────────────────────────────────────────────────────

function run() {
  const args = process.argv.slice(2).filter((a) => !a.startsWith("--"));
  const flags = process.argv.slice(2).filter((a) => a.startsWith("--"));
  const writeMode = flags.includes("--write");

  if (args.length === 0) {
    console.error(
      "Usage: node agent/ingest.js <declaration-file.json> [--write]\n\n" +
      "  Without --write: prints generated adapter, manifest entry, and registry line.\n" +
      "  With --write:    writes adapter to ui/components/modules/ and prints next steps."
    );
    process.exit(1);
  }

  const declPath = path.resolve(process.cwd(), args[0]);
  if (!fs.existsSync(declPath)) {
    console.error(`Declaration file not found: ${declPath}`);
    process.exit(1);
  }

  let declaration;
  try {
    declaration = JSON.parse(fs.readFileSync(declPath, "utf8"));
  } catch (err) {
    console.error(`Failed to parse declaration file: ${err.message}`);
    process.exit(1);
  }

  // Validate
  const { valid, errors } = validateDeclaration(declaration);
  if (!valid) {
    console.error("Declaration validation failed:\n");
    errors.forEach((e) => console.error(`  ✗  ${e}`));
    console.error("\nFix the declaration and try again.");
    process.exit(1);
  }

  const { modeType } = declaration;
  const adapterFilename = `${modeType}.tsx`;
  const adapterPath = path.join(MODULES_DIR, adapterFilename);

  // Generate outputs
  const adapterSrc = generateAdapter(declaration);
  const manifestEntry = generateManifestEntry(declaration);
  const registryLine = `  ${modeType}: ${modeType},`;

  if (writeMode) {
    // Write adapter file
    if (fs.existsSync(adapterPath)) {
      console.log(`\nAdapter already exists: ui/components/modules/${adapterFilename}`);
      console.log("Overwriting...\n");
    }
    fs.writeFileSync(adapterPath, adapterSrc, "utf8");
    console.log(`\n✓  Adapter written: ui/components/modules/${adapterFilename}\n`);

    console.log("─".repeat(60));
    console.log("NEXT STEPS\n");

    console.log("1. Add to MODULE_REGISTRY in ui/components/modules/index.ts:\n");
    console.log(`   import { ${modeType} } from "./${modeType}";`);
    console.log(`\n   // In MODULE_REGISTRY:`);
    console.log(`   ${registryLine}\n`);

    const existingEntry = (() => {
      try {
        const manifest = JSON.parse(fs.readFileSync(COMPONENTS_JSON, "utf8"));
        return (manifest.components || []).find((c) => c.name === modeType);
      } catch { return null; }
    })();

    if (existingEntry) {
      console.log(`2. manifest/components.json already has a "${modeType}" entry.`);
      console.log("   The adapter replaces the built-in implementation — no manifest change needed.\n");
    } else {
      console.log("2. Add this entry to manifest/components.json:\n");
      console.log(JSON.stringify(manifestEntry, null, 2));
      console.log("\n   Fill in [FILL IN] placeholders before running a build.\n");
    }

    console.log("3. Run the manifest validator to confirm registration:");
    console.log("   node agent/validate-manifest.js\n");

  } else {
    // Dry run — print everything
    console.log("─".repeat(60));
    console.log(`ADAPTER — ui/components/modules/${adapterFilename}\n`);
    console.log(adapterSrc);

    console.log("─".repeat(60));
    console.log("MANIFEST ENTRY — add to manifest/components.json \"components\" array\n");
    console.log(JSON.stringify(manifestEntry, null, 2));

    console.log("\n" + "─".repeat(60));
    console.log("REGISTRY — add to ui/components/modules/index.ts\n");
    console.log(`import { ${modeType} } from "./${modeType}";`);
    console.log(`\n// In MODULE_REGISTRY:\n${registryLine}`);

    console.log("\n" + "─".repeat(60));
    console.log("Run with --write to write the adapter file automatically.");
  }
}

// ─── Module exports ──────────────────────────────────────────────────────────

module.exports = { generateAdapter, generateManifestEntry };

// Run CLI when invoked directly
if (require.main === module) {
  run();
}
